# Generated by Django 2.0.5 on 2020-02-10 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(unique='True')),
                ('ename', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Empdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esal', models.IntegerField()),
                ('design', models.CharField(max_length=250)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Emp')),
            ],
        ),
    ]
